language: python
python: 2.7
env:
  - TOX_ENV=all
# don't test branches that might not build
branches:
  only:
    - master
    - development
install:
  - pip install coverage
  - pip install codecov
  - pip install tox
script:
  - tox
after_success:
  - codecov
